#!/bin/bash

export BORG_REPO=${BORG_REPO_BASE}/./${NODE_NAME}

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup ..."

if [[ "${BORG_MODE}" = "node" ]]; then
    info "Running in DaemonSet mode."
    BACKUP_PATTERNS=${BORG_NODE_PATTERNS}
    BACKUP_EXCLUDES=${BORG_NODE_EXCLUDES}
    BORGBACKUP_ARCHIVE_PREFIX=${NODE_NAME}
else
    BACKUP_PATTERNS=${BORG_PATTERNS}
    BACKUP_EXCLUDES=${BORG_EXCLUDES}
fi


borg create \
    --verbose \
    --filter AME \
    --list \
    --stats \
    --show-rc \
    --compression lz4 \
    --exclude-caches \
    --exclude-from=${BACKUP_EXCLUDES}  \
    --patterns-from=${BACKUP_PATTERNS}  \
    "$@" \
    ${BORG_REPO}::${BORGBACKUP_ARCHIVE_PREFIX}'-{now:%Y-%m-%d-%s}'

backup_exit=$?

info "Pruning repository ..."

borg prune                     \
    ${BORG_REPO}               \
    --verbose                  \
    --list                     \
    --show-rc                  \
    --keep-within   24H        \
    --keep-daily    7          \
    --keep-weekly   4          \
    --keep-monthly  6          \

prune_exit=$?

info_exit=$?

# use highest exit code as global exit code
global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))
global_exit=$(( global_exit > info_exit ? global_exit : info_exit ))

if [ ${global_exit} -eq 1 ];
then
    info "Backup and/or Prune finished with a warning!"
fi

if [ ${global_exit} -gt 1 ];
then
    info "Backup and/or Prune finished with an error!"
fi

exit ${global_exit}

borg-info

# end
