#!/bin/bash

# Ansible managed

if [ -f /root/.borg.cfg ]; then
    . /root/.borg.cfg
fi

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Prune interrupted >&2; exit 2' INT TERM

info "Pruning repository ..."

borg prune                     \
    ${BORG_REPO}               \
    --verbose                  \
    --list                     \
    --show-rc                  \
    --keep-within   24H        \
    --keep-daily    7          \
    --keep-weekly   4          \
    --keep-monthly  6          \

global_exit=$?

if [  ${global_exit} -gt 0 ];
then
    info "Prune finished with an error!"
fi

exit ${global_exit}

# end
