apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-borg-nfs-pvc
  labels:
    app: k8s-borg
    release: k8s-borg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  volumeName: k8s-borg-nfs-pv
  storageClassName: ''
  volumeMode: Filesystem

