apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-borg-ui-agent-pvc
  labels:
    app: k8s-borg
    release: k8s-borg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  volumeName: k8s-borg-ui-agent-pv
  storageClassName: ''
  volumeMode: Filesystem

