{{- /*
Copyright IO ANALYTICA. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-borg.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  cluster-s3-buckets: |
    {{- range .Values.cluster.s3Buckets }}
    {{ . }}
    {{- end }}
  cluster-include.patterns: |
    {{- range .Values.cluster.include }}
    {{ . }}
    {{- end }}
  cluster-exclude.patterns: |
    {{- range .Values.cluster.exclude }}
    {{ . }}
    {{- end }}
  node-include.patterns: |
    {{- range .Values.node.include }}
    {{ . }}
    {{- end }}
  node-exclude.patterns: |
    {{- range .Values.node.exclude }}
    {{ . }}
    {{- end }}
