{{- /*
Copyright IO ANALYTICA. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if not .Values.ssh.existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-ssh" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
stringData:
  id_ed25519: {{ required "ssh.privateKey is required (or set ssh.existingSecret)" .Values.ssh.privateKey | quote }}
  id_ed25519.pub: {{ .Values.ssh.publicKey | quote }}
  known_hosts: {{ required "ssh.knownHosts is required (or set ssh.existingSecret)" .Values.ssh.knownHosts | quote }}
{{- end }}
