{{- /*
Copyright IO ANALYTICA. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- $hasConfig := false }}
{{- range .Values.databases.postgres.instances }}{{- if .config }}{{- $hasConfig = true }}{{- end }}{{- end }}
{{- if and .Values.databases.postgres.enabled (not .Values.databases.postgres.existingSecret) $hasConfig }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-postgres" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
stringData:
  {{- range .Values.databases.postgres.instances }}
  {{- if .config }}
  {{ .name }}.conf: |
    {{- .config | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
