{{- /*
Copyright IO ANALYTICA. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.borgUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ui" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "k8s-borg.labels" (dict "context" $ "component" "ui") | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.borgUI.service.type }}
  selector: {{- include "k8s-borg.matchLabels" (dict "context" $ "component" "ui") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.borgUI.service.port }}
      targetPort: http
{{- end }}
