#!/usr/bin/env python3
"""Pick the Borg binaries this image should install, from the borg-ui manifest.

The Borg versions and their checksums are stated once, in the borg-ui submodule
(`app/api/borg_binaries.json`, generated by its refresh script from
`Dockerfile.runtime-base`). This image derives both from there so the pod agent
runs the same Borg as the server and as a node agent, with no second copy of a
version number or a digest to keep in step.

Prints one line per Borg major, for the given `docker buildx` TARGETARCH:

    borg1 <version> <sha256> <url>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# docker's TARGETARCH -> the architecture name Borg's assets are labelled with.
DOCKER_ARCH = {"amd64": "x86_64", "arm64": "aarch64"}


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit("usage: select-borg-binaries.py MANIFEST TARGETARCH")

    manifest = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    target = sys.argv[2]

    arch = DOCKER_ARCH.get(target)
    if arch is None:
        raise SystemExit(f"No published Borg binary for TARGETARCH={target}")

    for major, version in sorted(manifest["current"].items()):
        candidates = [b for b in manifest["binaries"][version] if b["arch"] == arch]
        if not candidates:
            raise SystemExit(f"Borg {version} publishes no {arch} binary")

        # Newest glibc build the base can run. The image is Debian, whose glibc
        # is well past every published build, so highest is simply best here.
        chosen = max(
            candidates,
            key=lambda b: tuple(int(part) for part in b["min_glibc"].split(".")),
        )
        url = manifest["release_url"].format(version=version, asset=chosen["asset"])
        print(f"borg{major} {version} {chosen['sha256']} {url}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
