---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-borg

resources:
  - k8s-borg-secret.yaml
  - k8s-borg-ssh-secret.yaml
  - k8s-borg-mariadb-secret.yaml
  - k8s-borg-postgres-secret.yaml
